export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "tertiary": "#D4A74B",
        "surface-tint": "#8A6BBF",
        "on-primary-fixed": "#2B1751",
        "primary-fixed-dim": "#D0BCFF",
        "on-tertiary-container": "#422F00",
        "surface-dim": "#F3F4F6",
        "surface-container": "#F3F4F6",
        "on-secondary": "#ffffff",
        "on-error-container": "#410002",
        "secondary-fixed": "#E8DEF8",
        "primary": "#8A6BBF",
        "on-secondary-fixed": "#1D192B",
        "tertiary-fixed-dim": "#EFB8C8",
        "secondary-fixed-dim": "#CCC2DC",
        "on-tertiary-fixed-variant": "#31111D",
        "secondary-container": "#F3F4F6",
        "surface-container-lowest": "#FFFFFF",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#FEF3C7",
        "surface-container-low": "#F9FAFB",
        "error-container": "#F9DEDC",
        "background": "#FFFFFF",
        "primary-fixed": "#EADDFF",
        "outline": "#9CA3AF",
        "on-primary": "#FFFFFF",
        "on-surface": "#111827",
        "inverse-surface": "#1F2937",
        "on-tertiary-fixed": "#31111D",
        "primary-container": "#F3F4F6",
        "on-secondary-fixed-variant": "#4A4458",
        "tertiary-fixed": "#FFD8E4",
        "inverse-primary": "#D0BCFF",
        "on-primary-fixed-variant": "#4F378B",
        "surface-container-high": "#E5E7EB",
        "on-surface-variant": "#4B5563",
        "on-error": "#FFFFFF",
        "surface-container-highest": "#D1D5DB",
        "on-secondary-container": "#111827",
        "inverse-on-surface": "#F9FAFB",
        "secondary": "#6B7280",
        "error": "#B3261E",
        "on-background": "#111827",
        "on-primary-container": "#111827",
        "surface-bright": "#FFFFFF",
        "outline-variant": "#D1D5DB",
        "surface": "#FFFFFF",
        "surface-variant": "#F3F4F6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "margin-mobile": "20px",
        "base": "8px",
        "section-gap": "120px",
        "gutter": "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "display-lg": ["Outfit"],
        "caption": ["Inter"],
        "headline-lg-mobile": ["Outfit"],
        "headline-lg": ["Outfit"],
        "body-lg": ["Inter"],
        "display-sm": ["Outfit"],
        "title-md": ["Outfit"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "display-lg": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-sm": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
